#include <iostream>
using namespace std;
int main()
{
    /*A movie in a local theater is in great demand. To help a local charity, the theater
    Owner has decided to donate to the charity a portion from the total amount generated
    from the movie. Write an Algorithm using the computational steps that prompts the user to input the
    1. Movie name
    2. Adult ticket price
    3. Child ticket price
    4. Number of adult tickets sold
    5. Number of child tickets sold
    6. Percentage of the amount to be donated to the charity.
    First of all, you have to calculate the total amount generated by the total sold tickets. Then after donating to the charity from the total amount, show the profit amount achieved from the movie on the Screen.*/
    string MVName = "abc";
    int TicPri, TotlTic, Total;
    float Charity;
    cout << "Enter Movie name:";
    cin >> MVName;
    cout << "Enter Adult ticket price: ";
    cin >> TicPri;
    cout << "Enter number of Adult ticket sold:";
    cin >> TotlTic;
    Charity = TicPri * TotlTic;
    cout << "Enter Child ticket price: ";
    cin >> TicPri;
    cout << "Enter number of Child ticket sold:";
    cin >> TotlTic;
    Total = TicPri * TotlTic;
    Total = Charity + Total;
    cout << "Collected Amount:" << Total;
    cout << endl
         << "Enter Charity Amount in Percentage:";
    cin >> Charity;
    Charity = Charity * 100;
    Total = Total - Charity;
    cout << "Profit is:" << Total;
}